jobs:
  flatpak:
    name: Flatpak
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Install dependencies
      run: sudo npm install -g less
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package -DskipTests
    - continue-on-error: true
      name: Install Flatpak dependencies
      run: 'sudo apt-get install -y flatpak flatpak-builder elfutils

        flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

        flatpak --user -y install flathub org.freedesktop.Platform/x86_64/22.08

        flatpak --user -y install flathub org.freedesktop.Sdk/x86_64/22.08

        flatpak --user -y install flathub org.freedesktop.Sdk.Compat.i386/x86_64/22.08

        flatpak --user -y install flathub org.freedesktop.Sdk.Extension.toolchain-i386/x86_64/22.08

        flatpak --user -y install flathub org.freedesktop.Sdk.Extension.openjdk11/x86_64/22.08

        flatpak --user -y install flathub org.freedesktop.Platform.Compat.i386/x86_64/22.08

        flatpak --user -y install flathub org.freedesktop.Platform.GL32.nvidia-460-39/x86_64/1.4

        '
    - continue-on-error: true
      name: Build flatpak
      run: 'cd phoenicis-dist/src/flatpak

        flatpak-builder build-dir org.phoenicis.playonlinux.yml --force-clean

        '
  macos-java-11:
    name: Mac OS (Java 11)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Install dependencies
      run: sudo npm install -g less
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package
    - continue-on-error: true
      name: Create package
      run: 'cd phoenicis-dist/src/scripts

        bash phoenicis-create-package.sh

        '
  ubuntu-java-11:
    name: Ubuntu (Java 11)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Install dependencies
      run: sudo npm install -g less
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package
    - continue-on-error: true
      name: Create package
      run: 'cd phoenicis-dist/src/scripts

        bash phoenicis-create-package.sh

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: Ubuntu
        path: phoenicis-dist/target/*.deb
  ubuntu-java-15:
    name: Ubuntu (Java 15)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 15
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: '15'
    - continue-on-error: true
      name: Install dependencies
      run: sudo npm install -g less
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
