jobs:
  java:
    name: Lint .java files
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repo
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Run Maven formatter
      run: mvn formatter:format
    - continue-on-error: true
      name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '*.java'
        author_email: git@phoenicis.org
        author_name: PhoenicisBot
        message: Lint .java files
name: Linter
on:
  repository_dispatch:
    types: trigger-ga___linter.yml
