jobs:
  run:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TRANSLATIONS_UPDATE }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Install dependencies
      run: sudo apt-get install -y gettext
    - continue-on-error: true
      name: Run Maven
      run: mvn -Pupdate-translations validate
    - continue-on-error: true
      id: check-changes
      name: Check changes
      run: git diff --numstat i18n/keys.pot |  awk '{ if($1 == 1 && $2 == 1) { exit
        1 } else exit 0 }'
    - continue-on-error: true
      if: steps.check-changes.outcome == 'success' && steps.check-changes.conclusion
        == 'success'
      name: Commit changes
      uses: EndBug/add-and-commit@v6
      with:
        add: '*.pot'
        author_email: git@phoenicis.org
        author_name: PhoenicisBot
        message: Update translations
name: Update translations
on:
  repository_dispatch:
    types: trigger-ga___update-translations.yml
